site_name: Sakura-Ji
site_url: https://Sakura-Ji.github.io
site_author: 纪博文
site_description: 纪博文的个人网站
nav:
    - 简介: index.md  
    - 编程语言:
        - Programing_Language/Introduction.md
        - C:
            - Programing_Language/C/C_language.md
            - main: Programing_Language/C/main.md
            - 指针: Programing_Language/C/pointer.md
            - 数组: Programing_Language/C/array.md
            - 链表: Programing_Language/C/link.md 
            - 文件: Programing_Language/C/floder.md
            - 堆栈: Programing_Language/C/stack.md
            - 模块: Programing_Language/C/keywords.md
    - 嵌入式编程:
        - EmbeddedSyS/Eintroduct.md
    - Linux系统:
        - LinuxSystem/Lintroduct.md
        - Gcc编译器: LinuxSystem/Gccinfo.md
        - MakeFile: LinuxSystem/Makefile.md
        - Linux文件: LinuxSystem/File.md
        - Linux进程: LinuxSystem/Multi-process.md
        - Linux通信: LinuxSystem/Communication.md
        - Linux线程: LinuxSystem/Posix.md
        - Linux网路: LinuxSystem/Internet.md
    - GodTool:
        - Tool/MapDepot.md
        - Tool/Testool.md
    - 思维导图:
        - MindMaps/Mind.md

theme:           
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: pink
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  #Site language       
  language: zh
  
  #Setting up navigation
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - search.share #搜索的内容链接可复制
    - navigation.footer #页脚出现上一页和下一页的链接
    - content.action.edit #配合ediu_uri使用 
    - content.code.annotate #代码块注释
#搜索插件      
plugins:
  - search:
      lang: en
  - tags

#代码块配置
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true # 显示行号
        # auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  #此配置启用内容选项卡，并允许在内容选项卡内嵌套任意内容，包括代码块和...更多内容选项卡
  - pymdownx.tabbed:
      alternate_style: true
  #定义列表和任务列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  #文中使用缩写，鼠标悬停显示所有文字
  - abbr
  #文中使用缩写，点击显示文章片段，待研究
  - pymdownx.snippets
  - attr_list #[Subscribe to our newsletter](#){ .md-button } 就是在链接到下一个内容的后面 加上{ .md-button } 使其展现的像按钮
  - md_in_html
  - pymdownx.superfences
  #表情图标:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables #启用表格
  #对图表的支持
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes #脚注
    #文本美化突出
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true # 固定标题位置为当前位置

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/lovestart.js

extra_css:
  - stylesheets/primarycolor.css


#页眉,页脚的配置
#右下角
extra:
  social:
    - icon: fontawesome/brands/github #图标
      link: https://github.com/Sakura-Ji #网址链接
      name: Github | Sakura-Ji #鼠标悬停显示

copyright: Sakura-Ji CC-BY-4.0 # 左下角的版权声明

repo_url: https://github.com/Sakura-Ji/Sakura-Ji.github.io #右上角github的链接跳转
repo_name: Sakura-Ji.github.io  #右上角github上的名字
icon:
      repo: fontawesome/brands/github #图标
edit_uri: edit/main/docs/ #点击可链接到github上

